# Generated by Django 2.2.9 on 2020-02-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200204_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='citycode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Abbr'),
        ),
        migrations.AlterField(
            model_name='city',
            name='displayseq',
            field=models.SmallIntegerField(unique=True, verbose_name='Display Sequence'),
        ),
    ]
